#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import agent
import json
import sys
import os
import secrets
import string

request = json.load(sys.stdin)
domain = request['domain'].lower()
node_id = os.environ['NODE_ID']
server_id = int(os.environ['MODULE_ID'].removeprefix("openldap"))
alphabet = string.ascii_letters + string.digits

rdb = agent.redis_connect()

# Retrieve the node VPN IP address to bind on it
agent.set_env('IP_ADDRESS', rdb.hget(f'node/{node_id}/vpn', 'ip_address'))

# Lookup a node for the given domain
for kopenldap in rdb.scan_iter(f'module/openldap*/environment'):
    penv = rdb.hgetall(kopenldap)
    if penv.get('DOMAIN', '') == domain:
        provision_type = 'join-domain'
        admin_password = penv['LDAP_ADMIN_PASSWORD']
        break
else: # No existing LDAP server for the given domain. Create a new one
    provision_type = 'new-domain'
    # Generate a random password for ldapservice
    admin_password = ''.join([secrets.choice(alphabet) for i in range(32)])

agent.set_env('PROVISION_TYPE', provision_type)

# Save values of optional parameters
agent.set_env('DOMAIN', domain)

# JSON Schema mandatory fields. We are sure they are present.
agent.set_env('LDAP_ADMIN_USERNAME', 'admin')
agent.set_env('LDAP_ADMIN_PASSWORD', admin_password)

agent.set_env('LDAP_ROOT', 'dc=' + domain.replace('.', ',dc='))
agent.set_env('SERVER_ID', str(server_id)) # value of olcServerID

agent.dump_env()
